### ISSUE TITLE
Suggestion: How about separate `outline` and `transparent` options from shape prop?

### ISSUE THREAD

**Issue by syug** [rakuten-rex/button#4]
### Description
Now we can choose shape prop from following options:

- default
- block
- circle
- **outline**
- pill
- square
- **transparent**

But technically `outline` and `transparent` option is able to be used in combination with other options such like `outline pill` or `transparent block` (<- not sure it's useful though).

### Proposal

(A) Boolean
```
<Button shape="pill" outline>Outline-Pill button</Button>
<Button shape="block" transparent>Transparent-Block button</Button>
```

(B) Variant (similar to [Material-UI](https://material-ui.com/components/buttons/#outlined-buttons))
```
<Button shape="pill" variant="outline">Outline-Pill button</Button>
<Button shape="block" variant="transparent">Transparent-Block button</Button>
```

Probably (B) is better because `outline` and  `transparent` option shouldn't be used together.

**Comment by claudio-moya** [comment]
done, check the new version!
